### ISSUE TITLE
redux-thunks topic: add some info about why we need thunks.

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/ACN-syllabus#2]
Just a little bit of text so that people are curious to follow the links.

Then add `ready: True` to the frontmatter

**Comment by sheenarbw** [comment]
@ToyaSims 
Who is doing this?  It's important to know

**Comment by ToyaSims** [comment]
Latoya

> @ToyaSims
> Who is doing this? It's important to know

Iam,sorry I thought I had commented my name

**Comment by ToyaSims** [comment]
issue claimed:latoya
