### ISSUE TITLE
Make sure top level web dev content has correct tags (teamwork!)

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/ACN-syllabus#24]
Take a look at all the contentlinks here: https://github.com/Umuzi-org/ACN-syllabus/blob/develop/content/syllabuses/web-dev.md

Each of the pages this links to can have "tags" associated with it in the frontmatter.  Go to each age and add the necessary tags.

**Comment by sheenarbw** [comment]
@ry-oc  if anyone runs out of stuff to do, this can be repeated for every syllabus.

**Comment by sheenarbw** [comment]
Latoya :)

**Comment by sheenarbw** [comment]
@ToyaSims @asradebe should this be closed?

**Comment by ToyaSims** [comment]
no,PR hasnt been merged yet

**Comment by muhesh-kumar** [comment]
Hello @sheenarbw ! I'd like to work on this. Can you explain a bit how I can help?

**Comment by ry-oc** [comment]
> Hello @sheenarbw ! I'd like to work on this. Can you explain a bit how I can help?

@muhesh-kumar this issue has been claimed already and is in PR, maybe check out these issues as they are similar: #58 #59 #60 

Also join the discord server for better communication and better access to assistance: https://discord.gg/YPTgKux
