### ISSUE TITLE
Consolidate sql folder structure

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/ACN-syllabus#47]
Back in the day, the way to categorise different pieces of content as different things was to put them into differet folders. You'll see that there are folders for "topics", "projects" and "workshops". Ths worked fine fora long time, but our syllabus offerings became way more complex, and frontmatter is awesome and versatile.

In an effort to make our syllabus easier to navigate, we'd like to have the content directory hierarchy less about the content type and more about what the content is about.

Please do the followin:
1. Make a new directory called `content/sql`
2. Make a markdown file in there called `_index.md`. For now that can just contain:
```
---
title: SQL
---
```
This will then show up in the navigation side bar.

3. Find all the things that are specific to pure sql and arrange them sensibly in this folder.  There is a whole bunch of cnotent about Python+sql, node+sql, kotlin+sql etc. For now please leave those things as they are. This is about plain simple sql only.

4. Run the linter. It's explained in the README. There are likely a bunch of links that need to be updated

5. Give yourself a pat on the back

**Comment by ry-oc** [comment]
Claimed by Babalwa
