### ISSUE TITLE
Consolidate all agile content

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/ACN-syllabus#55]
This is very similar to issue #54 

Basically, find all the content that has anything to do with Agile and move it into a folder called `/content/agile` 
Once that is done run the linter. Movint things probably would have broken a few links. 
Once all the links and things are fixed, you're done :)

**Comment by sheenarbw** [comment]
nkululek0

**Comment by muhesh-kumar** [comment]
Hello @sheenarbw !  I have moved everything related to agile into /content/agile. Then I ran linter, but I got an error, "no module named frontmatter found". Can you help me with this?
