### ISSUE TITLE
Make sure top level data eng content has correct tags (teamwork!)

### ISSUE THREAD

**Issue by ry-oc** [Umuzi-org/ACN-syllabus#58]
Take a look at all the contentlinks here: https://github.com/Umuzi-org/ACN-syllabus/blob/develop/content/syllabuses/data-eng.md

Each of the pages this links to can have "tags" associated with it in the frontmatter. Go to each age and add the necessary tags.

Similar to #24 refer to comments on PR https://github.com/Umuzi-org/ACN-syllabus/pull/38

**Comment by ToyaSims** [comment]
@asradebe claimed by?

**Comment by asradebe** [comment]
> @asradebe claimed by?

None. Might have been a mistake.

**Comment by asradebe** [comment]
> > @asradebe claimed by?
> 
> None. Might have been a mistake.

But wait let me find out, cause maybe there is someone working on it
