### ISSUE TITLE
Update git basic exercises

### ISSUE THREAD

**Issue by ry-oc** [Umuzi-org/ACN-syllabus#66]
update `projects/git-exercises/` with the changes below

1. Github recently changed some of their language so we need to update the exercises th match. Change all refrences to `master` to `main`
2. Many recruits fail to push the gitignore section and thus cannot be competent on the first submission. Update the gitignore section to add commit and push to the end of them.
3. Our syllabus has grown drastically in size, this is a problem for some recruits when they get to the section about cloning our repo, change the referances from `https://github.com/Umuzi-org/tech-department` to `https://github.com/Umuzi-org/a-repo-to-clone`

**Comment by ry-oc** [comment]
@BrownxGirl

**Comment by sagarmulchandani** [comment]
Hi @ry-oc  have made changes related to this. Please see the PR attached https://github.com/Umuzi-org/ACN-syllabus/pull/73
