### ISSUE TITLE
Create a useful topic on time management

### ISSUE THREAD

**Issue by ry-oc** [Umuzi-org/ACN-syllabus#68]
Check out the resources in this presentation https://docs.google.com/presentation/d/1gRAGqSma21RkbnfoCO2KM565EfGCf9m4ZuJ9S7mcyFc and create a topic that covers that info and anything additional you think should be covered. Feel free to link additional Resources

**Comment by mctraore** [comment]
I'm interested in working on this issue

**Comment by ry-oc** [comment]
@mctraore sure I have updated the status, please join our discord server as it makes comms easier :) https://discord.gg/3jRwWPm
