### ISSUE TITLE
Dead Link: 410 Deleted by Author

### ISSUE THREAD

**Issue by MondeAnna** [Umuzi-org/ACN-syllabus#801]
### Description:

Provided link leads to a deactivated/deleted account

### Steps to reproduce:

1. Open the "Clean Code for Data Science" [card](http://syllabus.africacode.net/topics/clean-code/)
2. Scroll to the bottm
3. Click on the [Medium}(https://medium.com/@rrfd/cookiecutter-data-science-organize-your-projects-atom-and-jupyter-2be7862f487e) link

### Expected behavior:

A  description of how to organise your projects using atom and Jupyter.

### Actual behavior:

![Screenshot from 2022-05-19 11-42-44](https://user-images.githubusercontent.com/78416274/169264180-c8d5edd0-93db-47f2-ad62-120c4d79cbb3.png)

***410*** status message

### Client Setup Information

- Browser Version: Google Chrome - Version 101.0.4951.64 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.4 LTS

**Comment by TheAbstract** [comment]
@MondeAnna this issue has been resolved so you can close it. Can't remember the PR but basically that link to the medium article has been replaced with a link to the original post on their [website](https://laptrinhx.com/cookiecutter-data-science-organize-your-projects-atom-and-jupyter-1729118267/).
